### ISSUE TITLE
update needed for latest conda

### ISSUE THREAD

**Issue by dougedmunds** [potassco/clingcon#98]
conda install -c potassco clingcon fails with Latest miniconda3 on winx64 
(Conda 22.11.1 Python 3.10.8 released December 22, 2022) 
- due to version of python included in Conda

**Comment by rkaminsk** [comment]
Yes, we should update the python version. But there are still (easy) ways to install.

First, you can install clingcon in a separate environment. The latest supported python version will be chosen:
```
conda install -n asp -c potassco clingcon
```
I would recommend to never install anything in the base environment to not mess up your conda installation.

Otherwise, you could also use clingcon from the conda-forge channel, which has support for the latest python version:
```
conda config --set channel_priority strict
conda install -n asp -c conda-forge clingcon
```
See also <https://github.com/conda-forge/clingo-feedstock>.
